# Generated by Django 5.0.4 on 2024-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventmember_alter_event_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.IntegerField(default=100),
        ),
    ]
