# Generated by Django 5.0.4 on 2024-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('message_upon_receipt', models.TextField()),
                ('buyed', models.BooleanField(default=False)),
                ('buyer', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
