# Generated by Django 5.0.4 on 2024-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_shopitem_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
