# Generated by Django 5.0.4 on 2024-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shopitem_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
